
name: Liquibase Multi-Env CI
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - sit
          - uat
 
jobs:
  liquibase-deploy:
    runs-on: self-hosted
 
    env:
      LIQUIBASE_VERSION: 4.24.0
      ENV: ${{ github.event.inputs.environment }}
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install unzip (required for Liquibase)
        run: sudo apt-get update && sudo apt-get install -y unzip
 
      - name: Install Liquibase
        run: |
          curl -sL https://github.com/liquibase/liquibase/releases/download/v${LIQUIBASE_VERSION}/liquibase-${LIQUIBASE_VERSION}.tar.gz 
          unzip -o liquibase.zip -d liquibase
          chmod +x liquibase/liquibase
          echo "${GITHUB_WORKSPACE}/liquibase" >> $GITHUB_PATH
          sudo mv liquibase /usr/local/bin/liquibase

      # - name: Download and Install Liquibase
      #   run: |
      #     curl -sL https://github.com/liquibase/liquibase/releases/latest/download/liquibase.zip -o liquibase.zip
      #     unzip -o liquibase.zip -d liquibase
      #     chmod +x liquibase/liquibase
      #     echo "${GITHUB_WORKSPACE}/liquibase" >> $GITHUB_PATH

      - name: Verify Liquibase Installation
        run: liquibase/liquibase --version

      - name: Run Liquibase Validate
        run: |
          liquibase && \
            --defaultsFile=liquibase/${ENV}/liquibase.properties && \
            --changeLogFile=liquibase/changelog.xml && \
            --logLevel=info \
          validate        
 
      - name: Dry Run SQL
        run: |
          liquibase \
            --defaultsFile=liquibase/${ENV}/liquibase.properties \
            --changeLogFile=liquibase/changelog.xml \
            --logLevel=info \
          updateSQL              
          
      - name: Update Database
        run: |
          liquibase \
            --defaultsFile=liquibase/${ENV}/liquibase.properties \
            --changeLogFile=liquibase/changelog.xml \
            --logLevel=info \
          update  
 