name: Liquibase CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  LIQUIBASE_VERSION: 4.20.0

jobs:
  # Job 1: Build and Validate
  # This job runs once, validates the changelog, and creates a single artifact
  validate_and_build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

    #   - name: Install Liquibase
    #     run: |
    #       wget https://github.com/liquibase/liquibase/releases/download/v${{ env.LIQUIBASE_VERSION }}/liquibase-${{ env.LIQUIBASE_VERSION }}.tar.gz
    #       mkdir -p liquibase
    #       tar -xzf liquibase-${{ env.LIQUIBASE_VERSION }}.tar.gz -C liquibase
    #       chmod +x liquibase/liquibase

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
