name: Liquibase Deployment on UAT & SIT
 
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          - uat
env:
  LIQUIBASE_VERSION: 4.20.0

jobs:
  # Stage 1: Build and Test in Dev Environment
  deply:
    runs-on: ubuntu-latest
    outputs:
      migration-needed: ${{ steps.check-changes.outputs.changes }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Liquibase
      run: |
        wget https://github.com/liquibase/liquibase/releases/download/v${{ env.LIQUIBASE_VERSION }}/liquibase-${{ env.LIQUIBASE_VERSION }}.tar.gz
        mkdir -p liquibase
        tar -xzf liquibase-${{ env.LIQUIBASE_VERSION }}.tar.gz -C liquibase
        chmod +x liquibase/liquibase
        
    - name: Download changelog artifact
      uses: actions/download-artifact@v4
      with:
        name: liquibase-changelog
        path: ./changelogs

#jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download changelog artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: liquibase-changelog
#           path: ./changelogs

#       - name: Set env secrets
#         run: |
#           if [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
#             echo "DB_URL=${{ secrets.SIT_DB_URL }}" >> $GITHUB_ENV
#             echo "DB_USER=${{ secrets.SIT_DB_USER }}" >> $GITHUB_ENV
#             echo "DB_PASSWORD=${{ secrets.SIT_DB_PASSWORD }}" >> $GITHUB_ENV
#           elif [[ "${{ github.event.inputs.environment }}" == "uat" ]]; then
#             echo "DB_URL=${{ secrets.UAT_DB_URL }}" >> $GITHUB_ENV
#             echo "DB_USER=${{ secrets.UAT_DB_USER }}" >> $GITHUB_ENV
#             echo "DB_PASSWORD=${{ secrets.UAT_DB_PASSWORD }}" >> $GITHUB_ENV
#           fi

#       - name: Run Liquibase Update on target env
#         uses: liquibase-github-actions/update@v4.x
#         with:
#           changelogFile: ./changelogs/db-changelog.xml
#           url: ${{ env.DB_URL }}
#           username: ${{ env.DB_USER }}
#           password: ${{ env.DB_PASSWORD }}
